version: '{branch}.{build}'

platform:
  - x64
  - x86

environment:
  PROJECT_NAME: php-timecop
  PHP_SDK_DIR: 'C:\php-sdk'
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PHP_SRC_URL: 'https://secure.php.net/distributions/php-7.2.2.tar.bz2'
      PHP_SDK_TOOLS_URL: 'https://github.com/OSTC/php-sdk-binary-tools/archive/php-sdk-2.1.0.zip'
      PHP_BUILD_CRT: vc15

install:
- cmd: >-
    choco feature enable -n=allowGlobalConfirmation

    cinst wget

#before_build:
#- cmd: >-
#    mkdir %PHP_SDK_DIR%
#
#    set PROJECT_DIR=C:\projects\%PROJECT_NAME%    
#
#    for /f %%F in ("%PHP_SRC_URL%") do set PHP_SRC_FILENAME=%%~nxF
#
#    set PHP_SRC_DIRNAME=%PHP_SRC_FILENAME:.tar.bz2=%
#
#    for /f %%F in ("%PHP_SDK_TOOLS_URL%") do set PHP_SDK_TOOLS_FILENAME=%%~nxF
#
#    set PHP_SDK_TOOLS_DIRNAME=php-sdk-binary-tools-%PHP_SDK_TOOLS_FILENAME:.zip=%
#
#    set PHP_SDK_STARTER_SCRIPT=phpsdk-%PHP_BUILD_CRT%-%PLATFORM%.bat
#
#    set PHP_BUILD_ROOT=%PHP_SDK_DIR%\phpdev\%PHP_BUILD_CRT%\%PLATFORM%\%PHP_SRC_DIRNAME%
#
#    wget %PHP_SDK_TOOLS_URL%
#
#    7z x -y  %PHP_SDK_TOOLS_FILENAME% -o%PHP_SDK_DIR%
#
#    cd %PHP_SDK_DIR%
#
#    if exist %PHP_SDK_TOOLS_DIRNAME% ( cd %PHP_SDK_TOOLS_DIRNAME% )
#
#    bin\phpsdk_buildtree.bat phpdev
#    
#    wget %PHP_SRC_URL%
#
#    7z x -so %PHP_SRC_BASENAME% | 7z x -si -ttar -o%PHP_BUILD_ROOT%\..
#
#    mkdir %PHP_BUILD_ROOT%\ext\%PROJECT_NAME%
#
#    xcopy %PROJECT_DIR% %PHP_BUILD_ROOT%\ext\%PROJECT_NAME% /s /e /y
#
#    bin\phpsdk_deps.bat -u


build_script:
  - appveyor\build.bat
  
#build_script:
#- cmd: >-
#    cd %PHP_BUILD_ROOT%
#    
#    buildconf.bat
#
#    configure.bat --disable-all --enable-phar --enable-json --enable-hash --enable-ctype --enable-filter --enable-tokenizer --with-iconv --with-openssl --with-dom --with-libxml --enable-zip --enable-timecop=shared --enable-cli --enable-zts --with-config-file-scan-dir=%PROJECT_DIR%\bin\modules.d --with-prefix=%PROJECT_DIR%\bin --with-php-build=deps
#
#    nmake
#
#    nmake install


#after_build:
#- cmd: >-
#    copy php.ini-development %PROJECT_DIR%\bin\php.ini
#
#    mkdir %PROJECT_DIR%\bin\modules.d
#
#    echo extension=php_timecop.dll >> %PROJECT_DIR%\bin\modules.d\php.ini


test_script:
  - appveyor\test.bat

#- cmd: >-
#    echo %PROJECT_DIR%
#
#    echo %TEST_PHP_EXECUTABLE%
#
#    cd %PROJECT_DIR%
#
#    if exist bin dir bin
#
#    if exist bin\ext dir bin\ext
#
#    if exist bin\modules.d dir bin\modules.d
#
#    "%TEST_PHP_EXECUTABLE%" %PHP_SRC_DIR%\run-tests.php --show-diff
#
#    exit /b %errorlevel%
