version: '{branch}.{build}'

environment:
  PROJECT_NAME: php-timecop
  PHP_SRC_DIR: C:\projects\php-src
  REPORT_EXIT_STATUS: 1
  NO_INTERACTION: 1
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      PHP_PACKAGE: 'https://secure.php.net/distributions/php-5.6.29.tar.bz2'
      MSVS_DIR: 'C:\Program Files (x86)\Microsoft Visual Studio 11.0'
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      PHP_PACKAGE: 'https://secure.php.net/distributions/php-7.1.7.tar.bz2'
      MSVS_DIR: 'C:\Program Files (x86)\Microsoft Visual Studio 14.0'
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PHP_PACKAGE: 'https://downloads.php.net/~remi/php-7.2.0alpha3.tar.bz2'
      MSVS_DIR: 'C:\Program Files (x86)\Microsoft Visual Studio 15.0'

install:
- cmd: >-
    set PROJECT_DIR=C:\projects\%PROJECT_NAME%

    set TEST_PHP_EXECUTABLE=%PROJECT_DIR%\bin\php.exe

    choco feature enable -n=allowGlobalConfirmation

    cinst wget

    mkdir %PROJECT_DIR%\bin

build_script:
- cmd: >-
    echo %APPVEYOR_BUILD_WORKER_IMAGE%

    echo %PROJECT_DIR%

    echo %TEST_PHP_EXECUTABLE%
    
    dir "C:\Program Files (x86)"

    "%MSVS_DIR%\VC\bin\vcvars32.bat"

    git clone https://github.com/php/php-src %PHP_SRC_DIR%

    cd %PHP_SRC_DIR%

    git checkout PHP-7.1

    wget http://windows.php.net/downloads/php-sdk/php-sdk-binary-tools-20110915.zip

    7z x -y php-sdk-binary-tools-20110915.zip -oC:\projects\php-sdk

    C:\projects\php-sdk\bin\phpsdk_setvars.bat

    mkdir %PHP_SRC_DIR%\ext\%PROJECT_NAME%

    xcopy %PROJECT_DIR% %PHP_SRC_DIR%\ext\%PROJECT_NAME% /s /e /y

    wget http://windows.php.net/downloads/php-sdk/deps-7.1-vc14-x86.7z

    7z x -y deps-7.1-vc14-x86.7z -o%PHP_SRC_DIR%

    buildconf.bat

    configure.bat --disable-all --enable-phar --enable-json --enable-hash --enable-ctype --enable-filter --enable-tokenizer --enable-zip --with-iconv --with-openssl --with-dom --with-libxml --enable-cli --enable-zts --enable-timecop=shared --with-config-file-scan-dir=%PROJECT_DIR%\bin\modules.d --with-prefix=%PROJECT_DIR%\bin --with-php-build=deps

    nmake

    nmake install

    copy php.ini-development %PROJECT_DIR%\bin\php.ini

    mkdir %PROJECT_DIR%\bin\modules.d

    echo extension=php_timecop.dll >> %PROJECT_DIR%\bin\modules.d\php.ini

test_script:
- cmd: >-
    echo %PROJECT_DIR%

    echo %TEST_PHP_EXECUTABLE%
    
    cd %PROJECT_DIR%

    dir bin\ext

    "%TEST_PHP_EXECUTABLE%" %PHP_SRC_DIR%\run-tests.php --show-diff

    exit /b %errorlevel%
