sudo: false
language: php

os:
  - linux

branches:
  except:
    - gh-pages
    - /^circleci-.*$/
    - /^wercker-.*$/

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - master

matrix:
    include:
        - os: osx
          language: generic

before_script:
  - phpize && ./configure && make
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update       ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install php71; fi

script:
  - make test REPORT_EXIT_STATUS=1 NO_INTERACTION=1 TESTS="--show-all" | tee tests-output.txt && if grep -q 'TEST SUMMARY$' tests-output.txt ; then exit 1 ; fi
