sudo: false
language: php

os:
  - linux

branches:
  except:
    - gh-pages
    - /^circleci-.*$/
    - /^wercker-.*$/

matrix:
    include:
        - php: 5.4
        - php: 5.5
        - php: 5.6
        - php: 7.0
        - php: 7.1
        - php: 7.2
        - php: master
        - os: osx
          osx_image: xcode9.2
          language: generic
          env: PHP_VERSION=php56
        - os: osx
          osx_image: xcode9.2
          language: generic
          env: PHP_VERSION=php70
        - os: osx
          osx_image: xcode9.2
          language: generic
          env: PHP_VERSION=php71
        - os: osx
          osx_image: xcode9.2
          language: generic
          env: PHP_VERSION=php72

before_script:
  - phpize && ./configure && make
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew tap homebrew/homebrew-php; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install $PHP_VERSION; fi

script:
  - make test REPORT_EXIT_STATUS=1 NO_INTERACTION=1 TESTS="--show-all" | tee tests-output.txt && if grep -q 'TEST SUMMARY$' tests-output.txt ; then exit 1 ; fi
